# kubernetes/backstage-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.backstage }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  GITHUB_TOKEN: {{ .Values.secrets.ghToken }}
  AZURE_TOKEN: {{ .Values.secrets.azToken }}
  APP_CONFIG_backend_baseUrl: {{ .Values.secrets.backendUrl }}
  ARGOCD_AUTH_TOKEN: {{ .Values.secrets.argocdToken }}
  IN_CLUSTER_SA_TOKEN: {{ .Values.secrets.incluster.token }}
  K8S_CLUSTER1_URL: {{ .Values.secrets.cluster1.url }}
  K8S_CLUSTER1_NAME: {{ .Values.secrets.cluster1.name }}
  K8S_CLUSTER1_SA_TOKEN: {{ .Values.secrets.cluster1.token }}
  APP_CONFIG_app_baseUrl: {{ .Values.secrets.backendUrl }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgres }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_HOST: {{ .Values.postgres.host }}
  POSTGRES_PORT: {{ .Values.postgres.port }}
  POSTGRES_USER: {{ .Values.postgres.username }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
